### ISSUE TITLE
Option to handle false positives

### ISSUE THREAD

**Issue by testman42** [m1l/Everything-Metric-Firefox#1]
Very often things that are not units of measurement get converted into metric.
Would it be possible to find a way to disable this behaviour?
This is the latest example of such behaviour: https://www.gamingonlinux.com/articles/d3d9-over-vulkan-gets-even-better-as-d9vk-021-lollihop-is-out.15080
(notice the conversion in the title)

From what I understand, the addon does not check if quotation marks are used to represent imperial units or are they used for actual quotation. At least I assume that is the case.

**Comment by m1l** [comment]
I'm working on improved support for regular quotes, but apostrophes are even trickier. As soon as there is a number followed with `'` it will be considered a foot... I'm not sure what would be the criteria for dismissing `/\d'/` unit as not being a proper unit. New version for Chrome (on store) has switch in options to completely disable converting `"`, I should add option to skip `'`, at least the apostrophe, since this is not the proper symbol for foot anyway. I'll fix it next week

**Comment by m1l** [comment]
In released 3.4 there are two options

- Convert "improper" symbols for foot and inch
- Convert inches written with "

Both are ON by default. In this case you can uncheck first option, which will only use Prime symbols. Unfortunately, people are "creative" in ways of writing all units, so there will be a lot of units that won't be converted, as most non-official sites still use apostrophes and quotes for these. If it gets annoying with everything ON, you may want to keep the extension Off, and when you need conversion, press Alt+M just to convert current page. If I think of a better way, I'll implement it
